# This rule is not used by the project poc-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to releases.opmodel.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: poc-controller
    app.kubernetes.io/managed-by: kustomize
  name: bundlerelease-viewer-role
rules:
- apiGroups:
  - releases.opmodel.dev
  resources:
  - bundlereleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - releases.opmodel.dev
  resources:
  - bundlereleases/status
  verbs:
  - get
