---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - impersonate
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - releases.opmodel.dev
  resources:
  - bundlereleases
  - modulereleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - releases.opmodel.dev
  resources:
  - bundlereleases/finalizers
  - modulereleases/finalizers
  verbs:
  - update
- apiGroups:
  - releases.opmodel.dev
  resources:
  - bundlereleases/status
  - modulereleases/status
  verbs:
  - get
  - patch
  - update
