apiVersion: releases.opmodel.dev/v1alpha1
kind: ModuleRelease
metadata:
  labels:
    app.kubernetes.io/name: poc-controller
    app.kubernetes.io/managed-by: kustomize
  name: modulerelease-sample
  namespace: default
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    name: test-hello
  module:
    path: opmodel.dev/test/hello
  prune: true
