apiVersion: releases.opmodel.dev/v1alpha1
kind: BundleRelease
metadata:
  labels:
    app.kubernetes.io/name: poc-controller
    app.kubernetes.io/managed-by: kustomize
  name: bundlerelease-sample
spec:
  # TODO(user): Add fields here
