apiVersion: releases.opmodel.dev/v1alpha1
kind: BundleRelease
metadata:
  labels:
    app.kubernetes.io/name: poc-controller
    app.kubernetes.io/managed-by: kustomize
  name: bundlerelease-sample
  namespace: default
spec:
  # NOTE: BundleRelease controller is not yet implemented.
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    name: test-hello
  prune: true
